update update :)

diff --git a/home/.zsh/config/functions b/home/.zsh/config/functions
--- a/home/.zsh/config/functions
+++ b/home/.zsh/config/functions
@@ -101,6 +101,12 @@ update_important_tools() {
   PACKAGES=(autojump brew-cask colordiff ctags direnv exiftool ffmpeg flvstreamer git imagemagick jhead macvim mussh node openssl pstree python rbenv readline redis rlwrap ruby-build sqlite tig unrar watch wget youtube-dl zsh)
   INSTALLED_PACKAGES=$(brew list ${PACKAGES})
 
+  # If brew list fails there are missing packages
+  if [[ "$?" != "0" ]]; then
+    echo "${ccyellow}Installing missing packages${ccend}"
+    brew install ${PACKAGES}
+  fi
+
   echo "${ccyellow}Updating rubygems${ccend}"
   gem update --system
 
@@ -108,18 +114,12 @@ update_important_tools() {
   gem install pry-debugger pry-byebug bundler git-up bond wirb spring spring-commands-rspec
 
   echo "${ccyellow}Installing important JS tools${ccend}"
-  npm install -g eslint gulp node-inspector
+  npm install -g eslint gulp node-inspector npm
 
   echo "${ccyellow}Checking homebrew update (updating if more than 2 packages updated)${ccend}"
   brew update
   UPDATES=$(brew outdated | wc -l)
   [[ "${UPDATES}" -ge "3" ]] && brew upgrade --all
-
-  echo "${ccyellow}Checking homebrew mandantory packages${ccend}"
-  if [[ ! "$?" == "0" ]]; then
-    echo "${ccyellow}Installing mandatory homebrew packages${ccend}"
-    brew install ${PACKAGES}
-  fi
 }
 
 # vim:ft=sh
